
version: '3'


services:

  webapp-dev:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    image: zentype:dev
    container_name: zentype-dev
    restart: always
    links:
      - mysql:mysql
      - redis:redis
    ports:
     - "4000:4000"
    volumes:
     - ./app:/app
     - /app/client/node_modules
    environment:
    # flask vars
     - FLASK_HOST=0.0.0.0
     - FLASK_PORT=80
     - FLASK_APP=main.py
     - FLASK_DEBUG=1
    # webpack server host and port
     - HOST=0.0.0.0
     - PORT=4000
    command: /usr/bin/supervisord

  mysql:
    image: mysql:5.7
    container_name: zentype-mysql-dev
    restart: always
    volumes:
     - ./mysql_store_dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=zentype

  adminer:
    image: adminer:4.6.2
    container_name: zentype-adminer-dev
    restart: always
    links:
      - mysql:mysql
    ports:
      - "8080:8080"

  redis:
    image: redis:4.0.9-alpine
    container_name: zentype-redis-dev
    restart: always
    volumes:
     - ./redis_store_dev:/data

